export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    tasbihCounter: "Tasbih Counter",
    nobleQuran: "Al-Qur'aan",
    hadithCollections: "Hadith Collections",
    namesOfAllah: "Asma Al-Husna",
    prayerTimes: "Prayer Times",
    qiblaFinder: "Qibla Finder",
    hijriCalendar: "Hijri Calendar",
    favourites: "Favourites",
    publications: "Publications",
    emotions: "Emotions",
    reminders: "Reminders",
    read: "Read",
    listen: "Listen",
    learn: "Learn",
    surah: "Surah",
    juz: "Juz",
    bookmark: "Bookmark",
    ayaat: "Ayaat",
    changeLanguage: "Change Language",
    appearance: "Appearance",
    notifications: "Notifications",
    audio: "Audio",
    system: "System",
    more: "More",
    savePreferences: "Save Preferences",
    search: "Search...",
    resume: "Resume",
    cancel: "Cancel",
    save: "Save",
    back: "Back",
    home: "Home",
      "settings": "Settings",
    "notificationsSub": "Daily Notifications, Reminder, Article, Time",
    "appearanceSub": "Theme, Arabic Font, Translation, Text Size & Preview",
    "audioSub": "Audio Speed, Reciter, Tasbih Vibration",
    "systemSub": "Download Over Wi-Fi, Check For Updates",
    "languageSub": "Change the language across the app",
    "moreSub": "FAQ, Tutorial Terms & Condition",
    "alKutubAlSittah": "Al-Kutub al-Sittah",
    "alKutubAlSittahSub": "The six canonical Hadith compilations of prophetic narrations.",
    "bukhari": "Sahih al-Bukhari",
    "bukhariSub": "By Imam Bukhari · {total} narrations",
    "muslim": "Sahih Muslim",
    "muslimSub": "By Imam Muslim · {total} narrations",
    "nasai": "Sunan an-Nasa'i",
    "nasaiSub": "By Imam An-Nasa'i · {total} narrations",
    "abudawud": "Sunan Abi Dawud",
    "abudawudSub": "By Imam Abu Dawud · {total} narrations",
    "tirmidhi": "Jami' at-Tirmidhi",
    "tirmidhiSub": "By Imam Al-Tirmidhi · {total} narrations",
    "ibnmajah": "Sunan Ibn Majah",
    "ibnmajahSub": "By Imam Ibn Majah · {total} narrations",
    "ummah": "Dua's for the Ummah",
    "morning": "Morning Adhkar",
    "evening": "Evening Adhkar",
    "sleep": "Before Sleep",
    "tahajjud": "Tahajjud",
    "salah": "Salah / Prayer",
    "after-salah": "After Salah",
    "istikharah": "Istikharah",
    "gatherings": "Gatherings",
    "difficulties": "Difficulties",
    "iman": "Protection of Iman",
    "hajj": "Hajj & Umrah",
    "travel": "Travel",
    "money": "Money & Debt",
    "social": "Social Life",
    "marriage": "Marriage & Family",
    "death": "Death & Grief",
    "nature": "Nature & Weather",
    "ruqyah": "Ruqyah",
    "daily-life": "Daily Life",
    "adhan": "Adhan & Masjid",
    "wudu": "Wudu & Lavatory",
    "masjid": "Masjid",
    "sickness": "Sickness / Illness",
    "forgiveness": "Forgiveness",
    "relatedArticles": "Related Articles",
    "playAll": "Play All",
    "favourite": "Favourite",
    "duaRefVirtue": "Dua Reference & Virtue",
    "virtue": "Virtue:",
    "explanation": "Explanation:",
    "liked": "Liked",
    "like": "Like",
    "duas": "Du'as",
    "readPercent": "read",
    "appVersion": "Islamic Hikmah v1.1.0",
    "goalSettings": "Goal Settings",
    "goalSettingsSub": "Choose which goals appear on your home screen daily checklist",
    "prayers": "Prayers",
    "dhikrAdhkar": "Dhikr & Adhkar",
    "otherDeeds": "Other Good Deeds",
    "fajr": "Fajr",
    "sunrise": "Sunrise",
    "dhuhr": "Dhuhr",
    "asr": "Asr",
    "maghrib": "Maghrib",
    "isha": "Isha",
    "qiyam": "Qiyam",
    "tahajjudSub": "Night prayer",
    "nafl": "Offer Nafl Prayer",
    "quran-5min": "Read Quran (5 Minutes)",
    "quran-5minSub": "Daily recitation",
    "surah-mulk": "Recite Surah Mulk",
    "surah-mulkSub": "Before sleeping",
    "morning-adhkar": "Morning Adhkar",
    "evening-adhkar": "Evening Adhkar",
    "sleep-adhkar": "Sleep Adhkar",
    "fast-monday": "Fast on Monday",
    "fast-mondaySub": "Repeats weekly",
    "fast-thursday": "Fast on Thursday",
    "fast-thursdaySub": "Repeats weekly",
    "surah-kahaf": "Recite Surah Kahaf",
    "surah-kahafSub": "Every Friday",
    "nextPrayer": "Next Prayer",
    "next": "NEXT",
    "allPrayersComplete": "All prayers complete",
    "alhamdulillah": "Alhamdulillah 🌙",
    "juristicMethod": "Juristic Method",
    "calculationMethod": "Calculation Method",
    "standardSchool": "Shafi / Maliki / Hanbali",
    "hanafiSchool": "Hanafi",
    "retry": "Retry",
    "close": "Close",
    "searchPageOrSurah": "Search Page or Surah",
    "searchSurahName": "Search Surah name...",
    "pageNo": "Page No. {page}",
    "continueRecitation": "Continue your recitation",
    "noRecentAudio": "No recent audio",
    "startListeningTrack": "Start listening to track progress",
    "resumeListening": "Resume listening",
    "seerah": "Seerah",
    "minRead": "{min} min read",
    "chapterNo": "Chapter {no}",
    "backToChapters": "Back to Chapters",

    "lifeOfProphet": "Life of the Prophet ﷺ",
    "sealedNectar": "Ar-Raheeq Al-Makhtum · The Sealed Nectar",
    "chaptersRead": "chapters read",
    "searchChapters": "Search chapters...",
    "all": "All",
    "markAsRead": "Mark as Read",
    "markedAsRead": "Marked as Read",
    "previous": "Previous",
    "next2": "Next",
    "completed": "Completed!",
    "endOfSeerah": "End of Seerah 🕊️",
    "chapterNotFound": "Chapter not found.",
    "currentPrayer": "Current Prayer",
    "viewAllPrayers": "View All Prayers",
    "mainDuas": "Main Duas",
    "otherDuas": "Other Duas",
    "completeGoalsToday": "Complete {total} goals today",
    "quran": "Quran",
    "page": "Page",
    "dhikr": "Dhikr",
    "other": "Other",
    "searchHadith": "Search hadith...",
    "chapter": "Chapter",
    "noResults": "No results found",
    "loading": "Loading...",
    "error": "Something went wrong",
    "share": "Share",
    "copy": "Copy",
    "copied": "Copied!",
    "arabic": "Arabic",
    "translation": "Translation",
    "transliteration": "Transliteration",
    "benefits": "Benefits",
    "count": "Count",
    "reset": "Reset",
    "done": "Done",
    "start": "Start",
    "stop": "Stop",
    "pause": "Pause",
    "play": "Play",
    "volume": "Volume",
    "speed": "Speed",
    "reciter": "Reciter",
    "darkMode": "Dark Mode",
    "lightMode": "Light Mode",
    "language": "Language",
    "aboutApp": "About App",
    "version": "Version",
    "rateApp": "Rate App",
    "contactUs": "Contact Us",
    "privacyPolicy": "Privacy Policy",
    "termsOfService": "Terms of Service",
    "noBookmarks": "No bookmarks yet",
    "addBookmark": "Add Bookmark",
    "removeBookmark": "Remove Bookmark",
    "bookmarked": "Bookmarked",
    "tapToRead": "Tap to read",
    "tapToListen": "Tap to listen",
    "verseNo": "Verse {no}",
    "pageNumber": "Page {no}",
    "ofTotal": "of {total}",
    "lastRead": "Last Read",
    "continueListening": "Continue Listening",
    "repeatMode": "Repeat",
    "shuffleMode": "Shuffle",
    "autoPlay": "Auto Play",
    "downloadAudio": "Download Audio",
    "selectReciter": "Select Reciter",
    "fontSize": "Font Size",
    "fontSizeSmall": "Small",
    "fontSizeMedium": "Medium",
    "fontSizeLarge": "Large",
    "showTranslation": "Show Translation",
    "showTransliteration": "Show Transliteration",
    "nightMode": "Night Mode",
    "wordByWord": "Word by Word",
    "tafsir": "Tafsir",
    "noInternet": "No internet connection",
    "tryAgain": "Try Again",
    "settings2": "Settings",
    "notifications2": "Notifications",
    "prayer": "Prayer",
    "prayerNotification": "Prayer Notification",
    "adhanSound": "Adhan Sound",
    "iqamahDelay": "Iqamah Delay",
    "method": "Method",
    "minutes": "minutes",
    "selectCity": "Select City",
    "useCurrentLocation": "Use Current Location",
    "latitude": "Latitude",
    "longitude": "Longitude",
    "timezone": "Timezone",
    "saveLocation": "Save Location",
    "locationSaved": "Location saved!",
    "locationError": "Could not get location",
    "qiblaDirection": "Qibla Direction",
    "qiblaAngle": "° from North",
    "compassCalibrate": "Calibrate Compass",
    "todayHijri": "Today in Hijri",
    "gregorianDate": "Gregorian Date",
    "hijriDate": "Hijri Date",
    "islamicEvents": "Islamic Events",
    "noEvents": "No events this month",
    "ramadan": "Ramadan",
    "eid": "Eid",
    "isra": "Isra' wal Mi'raj",
    "mawlid": "Mawlid an-Nabi",
    "ashura": "Ashura",
    "dhulhijja": "Dhul Hijja",
    "shaban": "Sha'ban",
    "rajab": "Rajab",
    "nameMeaning": "Meaning",
    "nameTranslit": "Transliteration",
    "nameArabic": "Arabic",
    "playName": "Play",
    "names99": "99 Names of Allah",
    "learnMore": "Learn More",
    "readMore": "Read More",
    "showLess": "Show Less",
    "expand": "Expand",
    "collapse": "Collapse",
    "sortBy": "Sort by",
    "filterBy": "Filter by",
    "alphabetical": "Alphabetical",
    "byNumber": "By Number",
    "byCategory": "By Category",
    "featured": "Featured",
    "new": "New",
    "popular": "Popular",
    "recent": "Recent",
    "seeAll": "See All",
    "showAll": "Show All",
    "hide": "Hide",
    "show": "Show",
    "enable": "Enable",
    "disable": "Disable",
    "off": "Off",
    "yes": "Yes",
    "no": "No",
    "ok": "OK",
    "confirm": "Confirm",
    "delete": "Delete",
    "edit": "Edit",
    "add": "Add",
    "remove": "Remove",
    "select": "Select",
    "update": "Update",
    "submit": "Submit",
    "send": "Send",
    "clear": "Clear",
    "clearAll": "Clear All",
    "selectAll": "Select All",
    "deselectAll": "Deselect All",
    "apply": "Apply",
    "reset2": "Reset",
    "defaultSettings": "Default Settings",
    "customSettings": "Custom Settings",
    "advanced": "Advanced",
    "basic": "Basic",
    "help": "Help",
    "faq": "FAQ",
    "tutorial": "Tutorial",
    "tips": "Tips",
    "feedback": "Feedback",
    "report": "Report",
    "share2": "Share",
    "invite": "Invite",
    "follow": "Follow",
    "subscribe": "Subscribe",
    "unsubscribe": "Unsubscribe",
    "moreInfo": "More Info",
    "details": "Details",
    "summary": "Summary",
    "overview": "Overview",
    "preview": "Preview",
    "fullScreen": "Full Screen",
    "exitFullScreen": "Exit Full Screen",
    "landscape": "Landscape",
    "portrait": "Portrait",
    "zoomIn": "Zoom In",
    "zoomOut": "Zoom Out",
  
    "mosqueFinder": "Masjid Finder",
    "halalFoodFinder": "Halal Food Finder",
    "pillarsOfIslam": "Pillars of Islam",
    "zakatCalculator": "Zakat Calculator",
    "hajjUmrahGuide": "Hajj & Umrah",
  },
  ar: {
    tasbihCounter: "عداد التسبيح",
    nobleQuran: "القرآن الكريم",
    hadithCollections: "كتب الحديث",
    namesOfAllah: "أسماء الله الحسنى",
    prayerTimes: "مواقيت الصلاة",
    qiblaFinder: "اتجاه القبلة",
    hijriCalendar: "التقويم الهجري",
    favourites: "المفضلة",
    publications: "المنشورات",
    emotions: "مشاعر",
    reminders: "التذكيرات",
    read: "قراءة",
    listen: "استماع",
    learn: "تعلم",
    surah: "سورة",
    juz: "جزء",
    bookmark: "المرجعية",
    ayaat: "آيات",
    changeLanguage: "تغيير اللغة",
    appearance: "المظهر",
    notifications: "الإشعارات",
    audio: "الصوت",
    system: "النظام",
    more: "المزيد",
    savePreferences: "حفظ الإعدادات",
    search: "بحث...",
    resume: "متابعة",
    cancel: "إلغاء",
    save: "حفظ",
    back: "رجوع",
      "settings": "الإعدادات",
    "notificationsSub": "الإشعارات اليومية، التذكيرات، المقالات، الوقت",
    "appearanceSub": "المظهر، الخط العربي، الترجمة، حجم النص والمعاينة",
    "audioSub": "سرعة الصوت، القارئ، اهتزاز التسبيح",
    "systemSub": "التنزيل عبر واي فاي، التحقق من التحديثات",
    "languageSub": "تغيير لغة التطبيق بالكامل",
    "moreSub": "الأسئلة الشائعة، الشروط والأحكام",
    "alKutubAlSittah": "الكتب الستة",
    "alKutubAlSittahSub": "كتب الحديث الستة المعتمدة لروايات النبي صلى الله عليه وسلم.",
    "bukhari": "صحيح البخاري",
    "bukhariSub": "للإمام البخاري · {total} حديثاً",
    "muslim": "صحيح مسلم",
    "muslimSub": "للإمام مسلم · {total} حديثاً",
    "nasai": "سنن النسائي",
    "nasaiSub": "للإمام النسائي · {total} حديثاً",
    "abudawud": "سنن أبي داود",
    "abudawudSub": "للإمام أبي داود · {total} حديثاً",
    "tirmidhi": "جامع الترمذي",
    "tirmidhiSub": "للإمام الترمذي · {total} حديثاً",
    "ibnmajah": "سنن ابن ماجه",
    "ibnmajahSub": "للإمام ابن ماجه · {total} حديثاً",
    "ummah": "أدعية للأمة",
    "morning": "أذكار الصباح",
    "evening": "أذكار المساء",
    "sleep": "أذكار النوم",
    "tahajjud": "صلاة التهجد",
    "salah": "أدعية الصلاة",
    "after-salah": "الأذكار بعد الصلاة",
    "istikharah": "دعاء الاستخارة",
    "gatherings": "كفارة المجلس",
    "difficulties": "الكروب واليسر",
    "iman": "حماية الإيمان",
    "hajj": "الحج والعمرة",
    "travel": "دعاء السفر",
    "money": "الرزق والدين",
    "social": "العلاقات الاجتماعية",
    "marriage": "النكاح والذرية",
    "death": "الموت والمصيبة",
    "nature": "الكون والطقس",
    "ruqyah": "الرقية الشرعية",
    "daily-life": "الحياة اليومية",
    "adhan": "الأذان والمسجد",
    "wudu": "الوضوء والخلاء",
    "masjid": "المسجد",
    "sickness": "المرض والعيادة",
    "forgiveness": "الاستغفار والتوبة",
    "relatedArticles": "المقالات المقترحة",
    "playAll": "تشغيل الكل",
    "favourite": "المفضلة",
    "duaRefVirtue": "مرجع الدعاء وفضله",
    "virtue": "الفضل:",
    "explanation": "الشرح:",
    "liked": "مضاف للمفضلة",
    "like": "إعجاب",
    "duas": "أدعية",
    "readPercent": "تمت قراءتها",
    "appVersion": "الحكمة الإسلامية v1.1.0",
    "goalSettings": "إعدادات الأهداف",
    "goalSettingsSub": "اختر الأهداف التي تظهر في قائمة التحقق اليومية على الشاشة الرئيسية",
    "prayers": "الصلوات",
    "dhikrAdhkar": "الأذكار والذكر",
    "otherDeeds": "أعمال صالحة أخرى",
    "fajr": "الفجر",
    "sunrise": "الشروق",
    "dhuhr": "الظهر",
    "asr": "العصر",
    "maghrib": "المغرب",
    "isha": "العشاء",
    "qiyam": "قيام الليل",
    "tahajjudSub": "صلاة الليل",
    "nafl": "صلاة نفل",
    "quran-5min": "قراءة القرآن (٥ دقائق)",
    "quran-5minSub": "التلاوة اليومية",
    "surah-mulk": "قراءة سورة الملك",
    "surah-mulkSub": "قبل النوم",
    "morning-adhkar": "أذكار الصباح",
    "evening-adhkar": "أذكار المساء",
    "sleep-adhkar": "أذكار النوم",
    "fast-monday": "صيام يوم الاثنين",
    "fast-mondaySub": "يتكرر أسبوعياً",
    "fast-thursday": "صيام يوم الخميس",
    "fast-thursdaySub": "يتكرر أسبوعياً",
    "surah-kahaf": "قراءة سورة الكهف",
    "surah-kahafSub": "كل يوم جمعة",
    "nextPrayer": "الصلاة التالية",
    "next": "التالي",
    "allPrayersComplete": "اكتملت جميع الصلوات",
    "alhamdulillah": "الحمد لله 🌙",
    "juristicMethod": "المذهب الفقهي",
    "calculationMethod": "طريقة الحساب",
    "standardSchool": "شافعي / مالكي / حنبلي",
    "hanafiSchool": "حنفي",
    "retry": "إعادة المحاولة",
    "close": "إغلاق",
    "searchPageOrSurah": "ابحث عن صفحة أو سورة",
    "searchSurahName": "ابحث عن اسم السورة...",
    "pageNo": "صفحة رقم {page}",
    "continueRecitation": "تابع تلاوتك",
    "noRecentAudio": "لا يوجد صوت حديث",
    "startListeningTrack": "ابدأ الاستماع لتتبع التقدم",
    "resumeListening": "استئناف الاستماع",
    "seerah": "السيرة النبوية",
    "minRead": "قراءة {min} دقائق",
    "chapterNo": "الفصل {no}",
    "backToChapters": "العودة إلى الفصول",

    "lifeOfProphet": "حياة النبي ﷺ",
    "sealedNectar": "الرحيق المختوم",
    "chaptersRead": "فصل مقروء",
    "searchChapters": "البحث في الفصول...",
    "all": "الكل",
    "markAsRead": "وضع علامة كمقروء",
    "markedAsRead": "تمت القراءة",
    "previous": "السابق",
    "next2": "التالي",
    "completed": "مكتمل!",
    "endOfSeerah": "نهاية السيرة 🕊️",
    "chapterNotFound": "الفصل غير موجود.",
    "currentPrayer": "الصلاة الحالية",
    "viewAllPrayers": "عرض جميع الصلوات",
    "mainDuas": "الأدعية الرئيسية",
    "otherDuas": "أدعية أخرى",
    "completeGoalsToday": "أتمم {total} هدفاً اليوم",
    "quran": "القرآن",
    "page": "صفحة",
    "dhikr": "ذكر",
    "other": "أخرى",
    "searchHadith": "البحث في الحديث...",
    "chapter": "فصل",
    "noResults": "لا نتائج",
    "loading": "جارٍ التحميل...",
    "error": "حدث خطأ",
    "share": "مشاركة",
    "copy": "نسخ",
    "copied": "تم النسخ!",
    "arabic": "عربي",
    "translation": "ترجمة",
    "transliteration": "نطق",
    "benefits": "الفوائد",
    "count": "عدد",
    "reset": "إعادة تعيين",
    "done": "تم",
    "start": "ابدأ",
    "stop": "إيقاف",
    "pause": "إيقاف مؤقت",
    "play": "تشغيل",
    "volume": "الصوت",
    "speed": "السرعة",
    "reciter": "القارئ",
    "darkMode": "الوضع الليلي",
    "lightMode": "الوضع النهاري",
    "language": "اللغة",
    "aboutApp": "عن التطبيق",
    "version": "الإصدار",
    "rateApp": "تقييم التطبيق",
    "contactUs": "اتصل بنا",
    "privacyPolicy": "سياسة الخصوصية",
    "termsOfService": "شروط الخدمة",
    "noBookmarks": "لا إشارات مرجعية بعد",
    "addBookmark": "إضافة إشارة مرجعية",
    "removeBookmark": "إزالة الإشارة المرجعية",
    "bookmarked": "تمت الإضافة للمرجعيات",
    "tapToRead": "اضغط للقراءة",
    "tapToListen": "اضغط للاستماع",
    "verseNo": "آية {no}",
    "pageNumber": "صفحة {no}",
    "ofTotal": "من {total}",
    "lastRead": "آخر قراءة",
    "continueListening": "متابعة الاستماع",
    "repeatMode": "تكرار",
    "shuffleMode": "عشوائي",
    "autoPlay": "تشغيل تلقائي",
    "downloadAudio": "تنزيل الصوت",
    "selectReciter": "اختر قارئاً",
    "fontSize": "حجم الخط",
    "fontSizeSmall": "صغير",
    "fontSizeMedium": "متوسط",
    "fontSizeLarge": "كبير",
    "showTranslation": "عرض الترجمة",
    "showTransliteration": "عرض النطق",
    "nightMode": "الوضع الليلي",
    "wordByWord": "كلمة بكلمة",
    "tafsir": "تفسير",
    "noInternet": "لا يوجد اتصال بالإنترنت",
    "tryAgain": "حاول مجدداً",
  
    "mosqueFinder": "مكتشف المساجد",
    "halalFoodFinder": "مكتشف الطعام الحلال",
    "pillarsOfIslam": "أركان الإسلام",
    "zakatCalculator": "حاسبة الزكاة",
    "hajjUmrahGuide": "دليل الحج والعمرة",
  },
  ur: {
    tasbihCounter: "تسبیح کاؤنٹر",
    nobleQuran: "القرآن",
    hadithCollections: "احادیث کی کتب",
    namesOfAllah: "اسماء الحسنیٰ",
    prayerTimes: "نماز کے اوقات",
    qiblaFinder: "قبلہ نما",
    hijriCalendar: "ہجری کیلنڈر",
    favourites: "پسندیدہ",
    publications: "اشاعتیں",
    emotions: "احساسات",
    reminders: "یاد دہانی",
    read: "پڑھیں",
    listen: "سنیں",
    learn: "سیکھیں",
    surah: "سورہ",
    juz: "پارہ",
    bookmark: "بک مارک",
    ayaat: "آیات",
    changeLanguage: "زبان تبدیل کریں",
    appearance: "ظہور",
    notifications: "نوٹیفیکیشن",
    audio: "آڈیو",
    system: "سسٹم",
    more: "مزید",
    savePreferences: "ترجیحات محفوظ کریں",
    search: "تلاش کریں...",
    resume: "شروع کریں",
    cancel: "منسوخ کریں",
    save: "محفوظ کریں",
    back: "واپس",
      "settings": "ترتیبات",
    "notificationsSub": "روزانہ نوٹیفیکیشن، یاد دہانی، آرٹیکل، وقت",
    "appearanceSub": "تھیم، عربی فونٹ، ترجمہ، متن کا سائز اور پیش نظارہ",
    "audioSub": "آڈیو اسپیڈ، قاری، تسبیح وائبریشن",
    "systemSub": "وائی فائی پر ڈاؤن لوڈ، اپ ڈیٹس چیک کریں",
    "languageSub": "پورے ایپ کی زبان تبدیل کریں",
    "moreSub": "سوالات، شرائط و ضوابط",
    "alKutubAlSittah": "الكتب الستة",
    "alKutubAlSittahSub": "احادیث نبوی صلی اللہ علیہ وسلم کی چھ مستند ترین کتابیں۔",
    "bukhari": "صحیح البخاری",
    "bukhariSub": "امام بخاری · {total} احادیث",
    "muslim": "صحیح مسلم",
    "muslimSub": "امام مسلم · {total} احادیث",
    "nasai": "سنن النسائی",
    "nasaiSub": "امام نسائی · {total} احادیث",
    "abudawud": "سنن ابی داود",
    "abudawudSub": "امام ابو داود · {total} احادیث",
    "tirmidhi": "جامع الترمذی",
    "tirmidhiSub": "امام ترمذی · {total} احادیث",
    "ibnmajah": "سنن ابن ماجہ",
    "ibnmajahSub": "امام ابن ماجہ · {total} احادیث",
    "ummah": "امت کے لیے دعائیں",
    "morning": "صبح کے اذکار",
    "evening": "شام کے اذکار",
    "sleep": "سونے سے پہلے کے اذکار",
    "tahajjud": "تہجد",
    "salah": "نماز کی دعائیں",
    "after-salah": "نماز کے بعد کے اذکار",
    "istikharah": "استخارہ",
    "gatherings": "مجلس کی دعا",
    "difficulties": "مشکلات اور آسانی",
    "iman": "ایمان کی حفاظت",
    "hajj": "حج اور عمرہ",
    "travel": "سفر کی دعا",
    "money": "رزق اور قرض",
    "social": "سماجی زندگی",
    "marriage": "نکاح اور خاندان",
    "death": "موت اور تعزیت",
    "nature": "کائنات اور موسم",
    "ruqyah": "رقیہ شرعیہ",
    "daily-life": "روزمرہ زندگی",
    "adhan": "اذان اور مسجد",
    "wudu": "وضو اور طہارت",
    "masjid": "مسجد",
    "sickness": "بیماری کی دعا",
    "forgiveness": "استغفار",
    "relatedArticles": "متعلقہ مضامین",
    "playAll": "سب چلائیں",
    "favourite": "پسندیدہ",
    "duaRefVirtue": "دعا کا حوالہ اور فضیلت",
    "virtue": "فضیلت:",
    "explanation": "وضاحت:",
    "liked": "پسند کیا گیا",
    "like": "پسند کریں",
    "duas": "دعائیں",
    "readPercent": "پڑھا گیا",
    "appVersion": "اسلامک حکمت v1.1.0",
    "goalSettings": "مقاصد کی ترتیبات",
    "goalSettingsSub": "منتخب کریں کہ کون سے مقاصد آپ کے ہوم اسکرین روزانہ چیک لسٹ میں نظر آئیں",
    "prayers": "نمازیں",
    "dhikrAdhkar": "اذکار و تسبیحات",
    "otherDeeds": "دیگر نیک اعمال",
    "fajr": "فجر",
    "sunrise": "طلوع آفتاب",
    "dhuhr": "ظہر",
    "asr": "عصر",
    "maghrib": "مغرب",
    "isha": "عشاء",
    "qiyam": "قیام",
    "tahajjudSub": "رات کی نماز",
    "nafl": "نفل نماز ادا کریں",
    "quran-5min": "قرآن کی تلاوت (5 منٹ)",
    "quran-5minSub": "روزانہ تلاوت",
    "surah-mulk": "سورہ ملک کی تلاوت",
    "surah-mulkSub": "سونے سے پہلے",
    "morning-adhkar": "صبح کے اذکار",
    "evening-adhkar": "شام کے اذکار",
    "sleep-adhkar": "سونے کے اذکار",
    "fast-monday": "پیر کا روزہ",
    "fast-mondaySub": "ہر ہفتے",
    "fast-thursday": "جمعرات کا روزہ",
    "fast-thursdaySub": "ہر ہفتے",
    "surah-kahaf": "سورہ کہف کی تلاوت",
    "surah-kahafSub": "ہر جمعہ کو",
    "nextPrayer": "اگلی نماز",
    "next": "اگلا",
    "allPrayersComplete": "تمام نمازیں مکمل ہو گئیں",
    "alhamdulillah": "الحمد للہ 🌙",
    "juristicMethod": "فقہی طریقہ کار",
    "calculationMethod": "حساب کا طریقہ",
    "standardSchool": "شافعی / مالکی / حنبلی",
    "hanafiSchool": "حنفی",
    "retry": "دوبارہ کوشش کریں",
    "close": "بند کریں",
    "searchPageOrSurah": "صفحہ یا سورہ تلاش کریں",
    "searchSurahName": "سورہ کا نام تلاش کریں...",
    "pageNo": "صفحہ نمبر {page}",
    "continueRecitation": "اپنی تلاوت جاری رکھیں",
    "noRecentAudio": "کوئی حالیہ آڈیو نہیں",
    "startListeningTrack": "ترقی کو ٹریک کرنے کے لیے سننا شروع کریں",
    "resumeListening": "سننا شروع کریں",
    "seerah": "سیرت نبوی",
    "minRead": "{min} منٹ مطالعہ",
    "chapterNo": "باب {no}",
    "backToChapters": "ابواب پر واپس جائیں",

    "lifeOfProphet": "نبی ﷺ کی زندگی",
    "sealedNectar": "الرحیق المختوم",
    "chaptersRead": "ابواب پڑھے",
    "searchChapters": "ابواب تلاش کریں...",
    "all": "سب",
    "markAsRead": "پڑھا ہوا نشان کریں",
    "markedAsRead": "پڑھا ہوا نشان کیا گیا",
    "previous": "پچھلا",
    "next2": "اگلا",
    "completed": "مکمل!",
    "endOfSeerah": "سیرت کا اختتام 🕊️",
    "chapterNotFound": "باب نہیں ملا",
    "currentPrayer": "موجودہ نماز",
    "viewAllPrayers": "تمام نمازیں دیکھیں",
    "mainDuas": "اہم دعائیں",
    "otherDuas": "دیگر دعائیں",
    "completeGoalsToday": "آج {total} اہداف مکمل کریں",
    "quran": "قرآن",
    "page": "صفحہ",
    "dhikr": "ذکر",
    "other": "دیگر",
  
    "mosqueFinder": "مسجد تلاش کنندہ",
    "halalFoodFinder": "حلال کھانے تلاش کنندہ",
    "pillarsOfIslam": "اسلام کے ارکان",
    "zakatCalculator": "زکوٰۃ کیلکولیٹر",
    "hajjUmrahGuide": "حج اور عمرہ گائیڈ",
  },
  hi: {
    tasbihCounter: "तस्बीह काउंटर",
    nobleQuran: "अल-क़ुरआन",
    hadithCollections: "हदीस संग्रह",
    namesOfAllah: "अस्मा-उल-हुस्ना",
    prayerTimes: "प्रार्थना का समय",
    qiblaFinder: "क़िबला लोकेटर",
    hijriCalendar: "हिजरी कैलेंडर",
    favourites: "पसंदीदा",
    publications: "प्रकाशन",
    emotions: "भावनाएँ",
    reminders: "रिमाइंडर्स",
    read: "पढ़ें",
    listen: "सुनें",
    learn: "सीखें",
    surah: "सूरा",
    juz: "पारा",
    bookmark: "बुकमार्क",
    ayaat: "आयात",
    changeLanguage: "भाषा बदलें",
    appearance: "प्रकटन",
    notifications: "अधिसूचना",
    audio: "ऑडियो",
    system: "प्रणाली",
    more: "अधिक",
    savePreferences: "प्राथमिकताएं सहेजें",
    search: "खोजें...",
    resume: "पुनः आरंभ",
    cancel: "रद्द करें",
    save: "सहेजें",
    back: "पीछे",
      "settings": "सेटिंग्स",
    "notificationsSub": "दैनिक सूचनाएं, अनुस्मारक, लेख, समय",
    "appearanceSub": "विषय, अरबी फ़ॉन्ट, अनुवाद, पाठ का आकार और पूर्वावलोकन",
    "audioSub": "ऑडियो गति, पाठक, तस्बीह कंपन",
    "systemSub": "वाई-फाई पर डाउनलोड करें, अपडेट की जांच करें",
    "languageSub": "पूरी ऐप की भाषा बदलें",
    "moreSub": "अक्सर पूछे जाने वाले प्रश्न, नियम और शर्तें",
    "alKutubAlSittah": "अल-कुतुब अल-सत्तह",
    "alKutubAlSittahSub": "पैगंबर के कथनों के छह प्रामाणिक हदीस संग्रह।",
    "bukhari": "सहीह अल-बुखारी",
    "bukhariSub": "इमाम बुखारी द्वारा · {total} हदीस",
    "muslim": "सहीह मुस्लिम",
    "muslimSub": "इमाम मुस्लिम द्वारा · {total} हदीस",
    "nasai": "सुनन अन-नसाई",
    "nasaiSub": "इमाम अन-नसाई द्वारा · {total} हदीस",
    "abudawud": "सुनन अबी दाऊद",
    "abudawudSub": "इमाम अबू दाऊद द्वारा · {total} हदीस",
    "tirmidhi": "जाभी अत-तिर्मिज़ी",
    "tirmidhiSub": "इमाम अल-तिर्मिज़ी द्वारा · {total} हदीस",
    "ibnmajah": "सुनन इब्ن माजाह",
    "ibnmajahSub": "इमाम इब्न माजाह द्वारा · {total} हदीस",
    "ummah": "उम्माह के लिए दुआएं",
    "morning": "सुबह के अज़कार",
    "evening": "शाम के अज़कार",
    "sleep": "सोने से पहले",
    "tahajjud": "तहज्जुद",
    "salah": "नमाज़ की दुआएं",
    "after-salah": "नмаज़ के बाद",
    "istikharah": "इस्तिखारा",
    "gatherings": "सभाएं",
    "difficulties": "कठिनाइयाँ",
    "iman": "इमान की सुरक्षा",
    "hajj": "हज और उमराह",
    "travel": "यात्रा",
    "money": "पैसा और कर्ज",
    "social": "सामाजिक जीवन",
    "marriage": "विवाह और परिवार",
    "death": "मृत्यु और शोक",
    "nature": "प्रकृति और मौसम",
    "ruqyah": "रुक्याह",
    "daily-life": "दैनिक जीवन",
    "adhan": "अज़ान और मस्जिद",
    "wudu": "વુઝુ અને શૌચાલય",
    "masjid": "मस्जिद",
    "sickness": "बीमारी",
    "forgiveness": "क्षमा",
    "relatedArticles": "संबंधित लेख",
    "playAll": "सब बजाएं",
    "favourite": "पसंदीदा",
    "duaRefVirtue": "दुआ संदर्भ और गुण",
    "virtue": "गुण:",
    "explanation": "स्पष्टीकरण:",
    "liked": "पसंद किया गया",
    "like": "पसंद",
    "duas": "दुआएं",
    "readPercent": "पढ़ा गया",
    "appVersion": "इस्लामिक हिकमा v1.1.0",
    "goalSettings": "लक्ष्य सेटिंग्स",
    "goalSettingsSub": "चुनें कि कौन से लक्ष्य आपकी होम स्क्रीन दैनिक चेकलिस्ट पर दिखाई दें",
    "prayers": "प्रार्थनाएं",
    "dhikrAdhkar": "अज़कार और तस्बीह",
    "otherDeeds": "अन्य अच्छे काम",
    "fajr": "फज्र",
    "sunrise": "सूर्योदय",
    "dhuhr": "धुहर",
    "asr": "असर",
    "maghrib": "मग़रिब",
    "isha": "इशा",
    "qiyam": "क़ियाम",
    "tahajjudSub": "रात की प्रार्थना",
    "nafl": "नफ़्ल नमाज़ पढ़ें",
    "quran-5min": "कुरान पढ़ें (5 मिनट)",
    "quran-5minSub": "दैनिक पाठ",
    "surah-mulk": "सूरह मुल्क पढ़ें",
    "surah-mulkSub": "सोने से पहले",
    "morning-adhkar": "सुबह के अज़कार",
    "evening-adhkar": "शाम के अज़कार",
    "sleep-adhkar": "सोने के अज़कार",
    "fast-monday": "सोमवार का व्रत",
    "fast-mondaySub": "साप्ताहिक पुनरावृत्ति",
    "fast-thursday": "गुरुवार का व्रत",
    "fast-thursdaySub": "साप्ताहिक पुनरावृत्ति",
    "surah-kahaf": "सूरह कहफ़ पढ़ें",
    "surah-kahafSub": "हर शुक्रवार",
    "nextPrayer": "अगली प्रार्थना",
    "next": "अगला",
    "allPrayersComplete": "सभी प्रार्थनाएं पूरी हुईं",
    "alhamdulillah": "अल्हम्दुलिल्लाह 🌙",
    "juristicMethod": "न्यायिक पद्धति",
    "calculationMethod": "गणना विधि",
    "standardSchool": "शाफ़ई / मालिकी / हनबली",
    "hanafiSchool": "हनाफ़ी",
    "retry": "पुनः प्रयास करें",
    "close": "बंद करें",
    "searchPageOrSurah": "पृष्ठ या सूरह खोजें",
    "searchSurahName": "सूरह का नाम खोजें...",
    "pageNo": "पृष्ठ संख्या {page}",
    "continueRecitation": "अपना पाठ जारी रखें",
    "noRecentAudio": "कोई हालिया ऑडियो नहीं",
    "startListeningTrack": "प्रगति को ट्रैक करने के लिए सुनना शुरू करें",
    "resumeListening": "सुनना जारी रखें",
    "seerah": "सीरत",
    "minRead": "{min} मिनट का पाठ",
    "chapterNo": "अध्याय {no}",
    "backToChapters": "अध्यायों पर वापस जाएं",

    "lifeOfProphet": "नबी ﷺ का जीवन",
    "sealedNectar": "अर-रहीकुल मख्तूम",
    "chaptersRead": "अध्याय पढ़े",
    "searchChapters": "अध्याय खोजें...",
    "all": "सभी",
    "markAsRead": "पढ़ा हुआ चिह्नित करें",
    "markedAsRead": "पढ़ा हुआ चिह्नित किया",
    "previous": "पिछला",
    "next2": "अगला",
    "completed": "पूर्ण!",
    "endOfSeerah": "सीरत का अंत 🕊️",
    "chapterNotFound": "अध्याय नहीं मिला",
    "currentPrayer": "वर्तमान नमाज़",
    "viewAllPrayers": "सभी नमाज़ें देखें",
    "mainDuas": "मुख्य दुआएं",
    "otherDuas": "अन्य दुआएं",
    "completeGoalsToday": "आज {total} लक्ष्य पूरे करें",
    "quran": "क़ुरआन",
    "page": "पृष्ठ",
    "dhikr": "ज़िक्र",
    "other": "अन्य",
  
    "mosqueFinder": "मस्जिद खोजक",
    "halalFoodFinder": "हलाल भोजन खोजक",
    "pillarsOfIslam": "इस्लाम के स्तंभ",
    "zakatCalculator": "जकात कैलकुलेटर",
    "hajjUmrahGuide": "हज और उमराह गाइड",
  },
  bn: {
    tasbihCounter: "তাসবিহ কাউন্টার",
    nobleQuran: "আল-কুরআন",
    hadithCollections: "হাদিস সংগ্রহ",
    namesOfAllah: "আসমাউল হুসনা",
    prayerTimes: "নামাজের সময়",
    qiblaFinder: "কিবলা কম্পাস",
    hijriCalendar: "হিজরি ক্যালেন্ডার",
    favourites: "পছন্দসই",
    publications: "প্রকাশনা",
    emotions: "অনুভূতি",
    reminders: "রিমাইন্ডার",
    read: "পড়ুন",
    listen: "শুনুন",
    learn: "শিখুন",
    surah: "সূরা",
    juz: "পারা",
    bookmark: "বুকমার্ক",
    ayaat: "আয়াত",
    changeLanguage: "ভাষা পরিবর্তন",
    appearance: "থিম ও ফন্ট",
    notifications: "নোটিফিকেশন",
    audio: "অডিও",
    system: "সিস্টেম",
    more: "অন্যান্য",
    savePreferences: "সংরक्षण করুন",
    search: "অনুসন্ধান...",
    resume: "পুনরায় শুরু",
    cancel: "বাতিল",
    save: "সংরক্ষণ",
    back: "ফিরে যান",
      "settings": "সেটিংস",
    "notificationsSub": "দৈনিক নোটিফিকেশন, রিমাইন্ডার, নিবন্ধ, সময়",
    "appearanceSub": "থিম, আরবি ফন্ট, অনুবাদ, টেক্সট সাইজ ও প্রিভিউ",
    "audioSub": "অডিও গতি, তেলাওয়াতকারী, তাসবিহ কম্পন",
    "systemSub": "ওয়াই-ফাই ডাউনলোড, আপডেট পরীক্ষা",
    "languageSub": "সম্পূর্ণ অ্যাপের ভাষা পরিবর্তন করুন",
    "moreSub": "জিজ্ঞাসাবাদ, নিয়ম ও শর্তাবলী",
    "alKutubAlSittah": "আল-কুতুব আল-সিত্তাহ",
    "alKutubAlSittahSub": "হাদীসের ছয়টি নির্ভরযোগ্য গ্রন্থ।",
    "bukhari": "সহীহ আল-বুখারী",
    "bukhariSub": "ইমাম বুখারী · {total}টি হাদিস",
    "muslim": "সহীহ মুসলিম",
    "muslimSub": "इमाम মুসলিম · {total}টি হাদিস",
    "nasai": "সूनान আন-নাসায়ী",
    "nasaiSub": "इमाम अन-নাসায়ী · {total}টি হাদিস",
    "abudawud": "সুনান আবু দাউদ",
    "abudawudSub": "इमाम अबू दাউद · {total}টি হাদিস",
    "tirmidhi": "জামে আত-তিরমিজী",
    "tirmidhiSub": "इमाम तिरमीजी · {total}টি হাদিস",
    "ibnmajah": "সুনান ইবনে মাজাহ",
    "ibnmajahSub": "इमाम इब्ने माजाह · {total}টি হাদিস",
    "ummah": "উম্মাহর জন্য দুয়া",
    "morning": "সকালের আজকার",
    "evening": "বিয়ালের আজকার",
    "sleep": "ঘুমানোর পূর্বে",
    "tahajjud": "তাহাজ্জুদ",
    "salah": "সালাত / নামাজ",
    "after-salah": "সালাত পরবর্তী",
    "istikharah": "ইস্তিখারা",
    "gatherings": "সভা সমাবেশ",
    "difficulties": "কঠিন পরিস্থিতি ও আনন্দ",
    "iman": "ঈমান রক্ষা",
    "hajj": "হজ্জ ও উমরাহ",
    "travel": "ভ্রমণ",
    "money": "অর্থ ও ঋণ",
    "social": "সামাজিকতা",
    "marriage": "বিবাহ ও পরিবার",
    "death": "मृत्यु ও শোক",
    "nature": "प्रकृति ও আবহাওয়া",
    "ruqyah": "রুকইয়াহ",
    "daily-life": "দৈনন্দিন জীবন",
    "adhan": "আজান ও মসজিদ",
    "wudu": "ওযু ও শૌচাগার",
    "masjid": "মসজিদ",
    "sickness": "অসুস্থতা",
    "forgiveness": "ক্ষমা প্রার্থনা",
    "relatedArticles": "সম্পর্কিত নিবন্ধ",
    "playAll": "সব প্লে করুন",
    "favourite": "পছন্দসই",
    "duaRefVirtue": "দুয়ার রেফারেন্স ও ফজিলত",
    "virtue": "ফজিলत:",
    "explanation": "ব্যাখ্যা:",
    "liked": "পছন্দ করা হয়েছে",
    "like": "পছন্দ",
    "duas": "দুয়া",
    "readPercent": "পঠিত",
    "appVersion": "ইসলামিক হিকমাহ v1.1.0",
    "goalSettings": "লক্ষ্য সেটিংস",
    "goalSettingsSub": "আপনার হোম স্ক্রীনের দৈনিক চেকলিস্টে কোন লক্ষ্যগুলি প্রদর্শিত হবে তা চয়ন করুন",
    "prayers": "নামাজসমূহ",
    "dhikrAdhkar": "জিকির ও আজকার",
    "otherDeeds": "অন্যান্য নেক আমল",
    "fajr": "ফজর",
    "sunrise": "সূর্যোদয়",
    "dhuhr": "যোহর",
    "asr": "আসর",
    "maghrib": "মাগরিব",
    "isha": "এশা",
    "qiyam": "কিয়াম",
    "tahajjudSub": "রাতের সালাত",
    "nafl": "নফল নামাজ আদায় করুন",
    "quran-5min": "কুরআন পাঠ (৫ মিনিট)",
    "quran-5minSub": "দৈনিক তেলাওয়াত",
    "surah-mulk": "সূরা মূলক তেলাওয়াত",
    "surah-mulkSub": "ঘুমানোর আগে",
    "morning-adhkar": "সকালের আজকার",
    "evening-adhkar": "বিয়ালের আজকার",
    "sleep-adhkar": "ঘুমানোর আজকার",
    "fast-monday": "সোমবারের রোজা",
    "fast-mondaySub": "সাপ্তাহিক পুনরাবৃত্তি",
    "fast-thursday": "বৃহস্পতিবারের রোজা",
    "fast-thursdaySub": "সাপ্তাহিক পুনরাবৃত্তি",
    "surah-kahaf": "সূরা কাহাফ তেলাওয়াত",
    "surah-kahafSub": "প্রতি শুক্রবার",
    "nextPrayer": "পরবর্তী নামাজ",
    "next": "পরবর্তী",
    "allPrayersComplete": "সব নামাজ সম্পন্ন",
    "alhamdulillah": "আলহামদুলিল্লাহ 🌙",
    "juristicMethod": "মাযহাবগত পদ্ধতি",
    "calculationMethod": "সময় গণনা পদ্ধতি",
    "standardSchool": "শাফেয়ী / মালিকী / হাম্বলী",
    "hanafiSchool": "হানাফী",
    "retry": "পুনরায় চেষ্টা করুন",
    "close": "বন্ধ করুন",
    "searchPageOrSurah": "পৃষ্ঠা বা সূরা অনুসন্ধান করুন",
    "searchSurahName": "সূরা নাম অনুসন্ধান করুন...",
    "pageNo": "পৃষ্ঠা নং {page}",
    "continueRecitation": "আপনার তেলাওয়াত চালিয়ে যান",
    "noRecentAudio": "কোন সাম্প্রতিক অডিও নেই",
    "startListeningTrack": "অগ্রগতি ট্র্যাক করতে শুনতে শুরু করুন",
    "resumeListening": "শোনা পুনরায় শুরু করুন",
    "seerah": "সীরাত",
    "minRead": "{min} মিনিট পঠিত",
    "chapterNo": "অধ্যায় {no}",
    "backToChapters": "অধ্যায়গুলোতে ফিরে যান",

    "lifeOfProphet": "নবী ﷺ এর জীবন",
    "sealedNectar": "আর-রাহিকুল মাখতুম",
    "chaptersRead": "অধ্যায় পড়া হয়েছে",
    "searchChapters": "অধ্যায় খুঁজুন...",
    "all": "সব",
    "markAsRead": "পঠিত হিসেবে চিহ্নিত করুন",
    "markedAsRead": "পঠিত হিসেবে চিহ্নিত",
    "previous": "আগের",
    "next2": "পরের",
    "completed": "সম্পন্ন!",
    "endOfSeerah": "সীরাহ সমাপ্ত 🕊️",
    "chapterNotFound": "অধ্যায় পাওয়া যায়নি",
    "currentPrayer": "বর্তমান নামাজ",
    "viewAllPrayers": "সকল নামাজ দেখুন",
    "mainDuas": "প্রধান দুআ",
    "otherDuas": "অন্যান্য দুআ",
    "completeGoalsToday": "আজ {total}টি লক্ষ্য পূরণ করুন",
    "quran": "কুরআন",
    "page": "পাতা",
    "dhikr": "যিকর",
    "other": "অন্যান্য",
  
    "mosqueFinder": "মসজিদ অনুসন্ধানকারী",
    "halalFoodFinder": "হালাল খাবার অনুসন্ধানকারী",
    "pillarsOfIslam": "ইসলামের স্তম্ভ",
    "zakatCalculator": "যাকাত ক্যালকুলেটর",
    "hajjUmrahGuide": "হজ্জ ও ওমরাহ গাইড",
  },
  id: {
    tasbihCounter: "Penghitung Tasbih",
    nobleQuran: "Al-Qur'an",
    hadithCollections: "Koleksi Hadis",
    namesOfAllah: "Asmaul Husna",
    prayerTimes: "Waktu Sholat",
    qiblaFinder: "Arah Kiblat",
    hijriCalendar: "Kalender Hijriah",
    favourites: "Favorit",
    publications: "Publikasi",
    emotions: "Emosi & Perasaan",
    reminders: "Pengingat",
    read: "Baca",
    listen: "Dengar",
    learn: "Pelajari",
    surah: "Surah",
    juz: "Juz",
    bookmark: "Bookmark",
    ayaat: "Ayat",
    changeLanguage: "Ubah Bahasa",
    appearance: "Tampilan",
    notifications: "Notifikasi",
    audio: "Audio",
    system: "Sistem",
    more: "Lainnya",
    savePreferences: "Simpan Pengaturan",
    search: "Cari...",
    resume: "Lanjutkan",
    cancel: "Batal",
    save: "Simpan",
    back: "Kembali",
  
    "lifeOfProphet": "Kehidupan Nabi ﷺ",
    "sealedNectar": "Ar-Rahiq Al-Makhtum",
    "chaptersRead": "bab dibaca",
    "searchChapters": "Cari bab...",
    "all": "Semua",
    "markAsRead": "Tandai Sudah Dibaca",
    "markedAsRead": "Sudah Ditandai Dibaca",
    "previous": "Sebelumnya",
    "next2": "Berikutnya",
    "completed": "Selesai!",
    "endOfSeerah": "Akhir Sirah 🕊️",
    "chapterNotFound": "Bab tidak ditemukan",
    "currentPrayer": "Sholat Saat Ini",
    "viewAllPrayers": "Lihat Semua Sholat",
    "mainDuas": "Doa Utama",
    "otherDuas": "Doa Lainnya",
    "completeGoalsToday": "Selesaikan {total} tujuan hari ini",
    "quran": "Al-Quran",
    "page": "Halaman",
    "dhikr": "Dzikir",
    "other": "Lainnya",
  
    "mosqueFinder": "Pencari Masjid",
    "halalFoodFinder": "Pencari Makanan Halal",
    "pillarsOfIslam": "Rukun Islam",
    "zakatCalculator": "Kalkulator Zakat",
    "hajjUmrahGuide": "Panduan Haji & Umrah",
  },
  tr: {
    tasbihCounter: "Zikirmatik",
    nobleQuran: "Kur'an-ı Kerim",
    hadithCollections: "Hadis Külliyatı",
    namesOfAllah: "Esma-i Hüsna",
    prayerTimes: "Namaz Vakitleri",
    qiblaFinder: "Kıble Pusulası",
    hijriCalendar: "Hicri Takvim",
    favourites: "Favoriler",
    publications: "Yayınlar",
    emotions: "Duygular",
    reminders: "Hatırlatıcılar",
    read: "Oku",
    listen: "Dinle",
    learn: "Öğren",
    surah: "Sure",
    juz: "Cüz",
    bookmark: "Yer İmi",
    ayaat: "Ayetler",
    changeLanguage: "Dili Değiştir",
    appearance: "Görünüm",
    notifications: "Bildirimler",
    audio: "Ses",
    system: "Sistem",
    more: "Daha Fazla",
    savePreferences: "Tercihleri Kaydet",
    search: "Ara...",
    resume: "Devam Et",
    cancel: "İptal",
    save: "Kaydet",
    back: "Geri",
  
    "lifeOfProphet": "Peygamberin Hayatı ﷺ",
    "sealedNectar": "Mühürlü Şarap",
    "chaptersRead": "bölüm okundu",
    "searchChapters": "Bölüm ara...",
    "all": "Tümü",
    "markAsRead": "Okundu Olarak İşaretle",
    "markedAsRead": "Okundu Olarak İşaretlendi",
    "previous": "Önceki",
    "next2": "Sonraki",
    "completed": "Tamamlandı!",
    "endOfSeerah": "Siyer Bitti 🕊️",
    "chapterNotFound": "Bölüm bulunamadı",
    "currentPrayer": "Mevcut Namaz",
    "viewAllPrayers": "Tüm Namazları Gör",
    "mainDuas": "Ana Dualar",
    "otherDuas": "Diğer Dualar",
    "completeGoalsToday": "Bugün {total} hedefi tamamla",
    "quran": "Kur'an",
    "page": "Sayfa",
    "dhikr": "Zikir",
    "other": "Diğer",
  
    "mosqueFinder": "Cami Bulucu",
    "halalFoodFinder": "Helal Yemek Bulucu",
    "pillarsOfIslam": "İslam'ın Şartları",
    "zakatCalculator": "Zekat Hesaplayıcı",
    "hajjUmrahGuide": "Hac ve Umre Rehberi",
  },
  fr: {
    tasbihCounter: "Tasbih / Chapelet",
    nobleQuran: "Le Saint Coran",
    hadithCollections: "Collections de Hadith",
    namesOfAllah: "Asma Al-Husna",
    prayerTimes: "Heures de Prière",
    qiblaFinder: "Boussole de la Qibla",
    hijriCalendar: "Calendrier Hijri",
    favourites: "Favoris",
    publications: "Publications",
    emotions: "Émotions",
    reminders: "Rappels",
    read: "Lire",
    listen: "Écouter",
    learn: "Apprendre",
    surah: "Sourate",
    juz: "Juz",
    bookmark: "Signet",
    ayaat: "Versets",
    changeLanguage: "Changer de Langue",
    appearance: "Apparence",
    notifications: "Notifications",
    audio: "Audio",
    system: "Système",
    more: "Plus",
    savePreferences: "Enregistrer",
    search: "Rechercher...",
    resume: "Reprendre",
    cancel: "Annuler",
    save: "Enregistrer",
    back: "Retour",
  
    "lifeOfProphet": "Vie du Prophète ﷺ",
    "sealedNectar": "Ar-Rahiq Al-Makhtum",
    "chaptersRead": "chapitres lus",
    "searchChapters": "Rechercher des chapitres...",
    "all": "Tout",
    "markAsRead": "Marquer comme lu",
    "markedAsRead": "Marqué comme lu",
    "previous": "Précédent",
    "next2": "Suivant",
    "completed": "Terminé!",
    "endOfSeerah": "Fin de la Sîra 🕊️",
    "chapterNotFound": "Chapitre non trouvé",
    "currentPrayer": "Prière actuelle",
    "viewAllPrayers": "Voir toutes les prières",
    "mainDuas": "Douas principales",
    "otherDuas": "Autres douas",
    "completeGoalsToday": "Compléter {total} objectifs aujourd'hui",
    "quran": "Coran",
    "page": "Page",
    "dhikr": "Dhikr",
    "other": "Autre",
  
    "mosqueFinder": "Chercheur de Mosquées",
    "halalFoodFinder": "Chercheur de Nourriture Halal",
    "pillarsOfIslam": "Les piliers de l'Islam",
    "zakatCalculator": "Calculateur de Zakat",
    "hajjUmrahGuide": "Guide Hajj & Omra",
  },
  es: {
    tasbihCounter: "Contador de Tasbih",
    nobleQuran: "El Noble Corán",
    hadithCollections: "Colecciones de Hadiz",
    namesOfAllah: "Asma Al-Husna",
    prayerTimes: "Horarios de Oración",
    qiblaFinder: "Brújula de Qibla",
    hijriCalendar: "Calendario Hégira",
    favourites: "Favoritos",
    publications: "Publicaciones",
    emotions: "Emociones",
    reminders: "Recordatorios",
    read: "Leer",
    listen: "Escuchar",
    learn: "Aprender",
    surah: "Sura",
    juz: "Juz",
    bookmark: "Marcador",
    ayaat: "Versículos",
    changeLanguage: "Cambiar Idioma",
    appearance: "Apariencia",
    notifications: "Notificaciones",
    audio: "Audio",
    system: "Sistema",
    more: "Más",
    savePreferences: "Guardar Ajustes",
    search: "Buscar...",
    resume: "Reanudar",
    cancel: "Cancelar",
    save: "Guardar",
    back: "Atrás",
  
    "lifeOfProphet": "Vida del Profeta ﷺ",
    "sealedNectar": "El Néctar Sellado",
    "chaptersRead": "capítulos leídos",
    "searchChapters": "Buscar capítulos...",
    "all": "Todo",
    "markAsRead": "Marcar como leído",
    "markedAsRead": "Marcado como leído",
    "previous": "Anterior",
    "next2": "Siguiente",
    "completed": "¡Completado!",
    "endOfSeerah": "Fin de la Sira 🕊️",
    "chapterNotFound": "Capítulo no encontrado",
    "currentPrayer": "Oración actual",
    "viewAllPrayers": "Ver todas las oraciones",
    "mainDuas": "Duas principales",
    "otherDuas": "Otras duas",
    "completeGoalsToday": "Completar {total} metas hoy",
    "quran": "Corán",
    "page": "Página",
    "dhikr": "Dhikr",
    "other": "Otro",
  
    "mosqueFinder": "Buscador de Mezquitas",
    "halalFoodFinder": "Buscador de Comida Halal",
    "pillarsOfIslam": "Pilares del Islam",
    "zakatCalculator": "Calculadora de Zakat",
    "hajjUmrahGuide": "Guía de Hajj y Umrah",
  },
  fa: {
    tasbihCounter: "صلوات شمار",
    nobleQuran: "قرآن کریم",
    hadithCollections: "کتب حدیث",
    namesOfAllah: "اسماء الحسنی",
    prayerTimes: "اوقات شرعی",
    qiblaFinder: "قبله نما",
    hijriCalendar: "تقویم هجری",
    favourites: "علاقه‌مندی‌ها",
    publications: "مطالب و مقالات",
    emotions: "احساسات",
    reminders: "یادآورها",
    read: "خواندن",
    listen: "شنیدن",
    learn: "آموزش",
    surah: "سوره",
    juz: "جزء",
    bookmark: "نشانک",
    ayaat: "آیات",
    changeLanguage: "تغییر زبان",
    appearance: "ظاهر",
    notifications: "اعلان‌ها",
    audio: "صدا",
    system: "سیستم",
    more: "بیشتر",
    savePreferences: "ذخیره تنظیمات",
    search: "جستجو...",
    resume: "ادامه",
    cancel: "لغو",
    save: "ذخیره",
    back: "برگشت",
  
    "lifeOfProphet": "زندگی پیامبر ﷺ",
    "sealedNectar": "الرحیق المختوم",
    "chaptersRead": "فصل خوانده شد",
    "searchChapters": "جستجوی فصل‌ها...",
    "all": "همه",
    "markAsRead": "علامت‌گذاری به عنوان خوانده شده",
    "markedAsRead": "علامت‌گذاری شد",
    "previous": "قبلی",
    "next2": "بعدی",
    "completed": "کامل شد!",
    "endOfSeerah": "پایان سیره 🕊️",
    "chapterNotFound": "فصل یافت نشد",
    "currentPrayer": "نماز فعلی",
    "viewAllPrayers": "دیدن همه نمازها",
    "mainDuas": "دعاهای اصلی",
    "otherDuas": "دعاهای دیگر",
    "completeGoalsToday": "امروز {total} هدف را تکمیل کنید",
    "quran": "قرآن",
    "page": "صفحه",
    "dhikr": "ذکر",
    "other": "دیگر",
  
    "mosqueFinder": "مسجد یاب",
    "halalFoodFinder": "غذای حلال یاب",
    "pillarsOfIslam": "ارکان اسلام",
    "zakatCalculator": "ماشین حساب زکات",
    "hajjUmrahGuide": "راهنمای حج و عمره",
  },
  ha: {
    tasbihCounter: "Lissafin Tasbihi",
    nobleQuran: "Al-Kur'ani",
    hadithCollections: "Littattafan Hadisi",
    namesOfAllah: "Asma'ul Husna",
    prayerTimes: "Lokutan Sallah",
    qiblaFinder: "Neman Kibla",
    hijriCalendar: "Hijri Calendar",
    favourites: "Abubuwan So",
    publications: "Wallafe-wallafe",
    emotions: "Natsuwa",
    reminders: "Tuna-tuna",
    read: "Karatu",
    listen: "Sauraro",
    learn: "Koyi",
    surah: "Surah",
    juz: "Juzi",
    bookmark: "Alama",
    ayaat: "Ayoyi",
    changeLanguage: "Canza Harshe",
    appearance: "Fasali",
    notifications: "Sanarwa",
    audio: "Sauti",
    system: "Tsarin App",
    more: "Karin Bayani",
    savePreferences: "Ajiye Bayani",
    search: "Nema...",
    resume: "Ci gaba",
    cancel: "Soke",
    save: "Ajiye",
    back: "Koma baya",
  
    "lifeOfProphet": "Rayuwar Annabi ﷺ",
    "sealedNectar": "Ar-Rahiqul Makhtum",
    "chaptersRead": "surori da aka karanta",
    "searchChapters": "Nemi surori...",
    "all": "Duka",
    "markAsRead": "Nuna an Karanta",
    "markedAsRead": "An Nuna an Karanta",
    "previous": "Baya",
    "next2": "Gaba",
    "completed": "An Kammala!",
    "endOfSeerah": "Ƙarshen Sirah 🕊️",
    "chapterNotFound": "Ba a sami surori ba",
    "currentPrayer": "Sallah ta Yanzu",
    "viewAllPrayers": "Duba Duk Salloli",
    "mainDuas": "Manyan Addu'o'i",
    "otherDuas": "Wasu Addu'o'i",
    "completeGoalsToday": "Kammala manufofi {total} yau",
    "quran": "Alqur'ani",
    "page": "Shafi",
    "dhikr": "Zikiri",
    "other": "Wasu",
  
    "mosqueFinder": "Neman Masallaci",
    "halalFoodFinder": "Neman Abincin Halal",
    "pillarsOfIslam": "Pillars of Islam",
    "zakatCalculator": "Zakat Calculator",
    "hajjUmrahGuide": "Hajj & Umrah",
  },
  ms: {
    tasbihCounter: "Penghitung Tasbih",
    nobleQuran: "Al-Quran",
    hadithCollections: "Koleksi Hadis",
    namesOfAllah: "Asmaul Husna",
    prayerTimes: "Waktu Solat",
    qiblaFinder: "Arah Kiblat",
    hijriCalendar: "Kalender Hijriah",
    favourites: "Kegemaran",
    publications: "Penerbitan",
    emotions: "Emosi & Perasaan",
    reminders: "Peringatan",
    read: "Baca",
    listen: "Dengar",
    learn: "Belajar",
    surah: "Surah",
    juz: "Juzuk",
    bookmark: "Penanda Buku",
    ayaat: "Ayat",
    changeLanguage: "Tukar Bahasa",
    appearance: "Paparan",
    notifications: "Pemberitahuan",
    audio: "Audio",
    system: "Sistem",
    more: "Lain-lain",
    savePreferences: "Simpan Tetapan",
    search: "Cari...",
    resume: "Teruskan",
    cancel: "Batal",
    save: "Simpan",
    back: "Kembali",
  
    "lifeOfProphet": "Kehidupan Nabi ﷺ",
    "sealedNectar": "Ar-Rahiqul Makhtum",
    "chaptersRead": "bab dibaca",
    "searchChapters": "Cari bab...",
    "all": "Semua",
    "markAsRead": "Tandakan Sudah Dibaca",
    "markedAsRead": "Telah Ditandakan Dibaca",
    "previous": "Sebelumnya",
    "next2": "Seterusnya",
    "completed": "Selesai!",
    "endOfSeerah": "Tamat Sirah 🕊️",
    "chapterNotFound": "Bab tidak ditemui",
    "currentPrayer": "Solat Semasa",
    "viewAllPrayers": "Lihat Semua Solat",
    "mainDuas": "Doa Utama",
    "otherDuas": "Doa Lain",
    "completeGoalsToday": "Selesaikan {total} matlamat hari ini",
    "quran": "Al-Quran",
    "page": "Halaman",
    "dhikr": "Zikir",
    "other": "Lain",
  
    "mosqueFinder": "Pencari Masjid",
    "halalFoodFinder": "Pencari Makanan Halal",
    "pillarsOfIslam": "Rukun Islam",
    "zakatCalculator": "Kalkulator Zakat",
    "hajjUmrahGuide": "Panduan Haji & Umrah",
  },
  ta: {
    tasbihCounter: "தஸ்பீஹ் கவுண்டர்",
    nobleQuran: "திருக்குர்ஆன்",
    hadithCollections: "ஹதீஸ் தொகுப்புகள்",
    namesOfAllah: "அஸ்மாவுல் ஹுஸ்னா",
    prayerTimes: "தொழுகை நேரங்கள்",
    qiblaFinder: "கிப்லா திசைகாட்டி",
    hijriCalendar: "ஹிஜிரி காலண்டர்",
    favourites: "விருப்பமானவை",
    publications: "கட்டுரைகள்",
    emotions: "உணர்ச்சிகள்",
    reminders: "நினைவூட்டல்கள்",
    read: "ஓதுக",
    listen: "கேட்க",
    learn: "கற்க",
    surah: "அத்தியாயம்",
    juz: "ஜுஸ்",
    bookmark: "புக்மார்க்",
    ayaat: "வசனங்கள்",
    changeLanguage: "மொழியை மாற்றுக",
    appearance: "தோற்றம்",
    notifications: "அறிவிப்புகள்",
    audio: "ஆடியோ",
    system: "அமைப்பு",
    more: "மேலும்",
    savePreferences: "சேமிக்க",
    search: "தேடுக...",
    resume: "தொடர்க",
    cancel: "ரத்து செய்",
    save: "சேமி",
    back: "பின்செல்க",
  
    "lifeOfProphet": "நபி ﷺ வாழ்க்கை",
    "sealedNectar": "அர்-ரஹீக்குல் மக்தூம்",
    "chaptersRead": "அத்தியாயங்கள் படித்தது",
    "searchChapters": "அத்தியாயங்கள் தேடுக...",
    "all": "அனைத்தும்",
    "markAsRead": "படித்தது என்று குறி இடுக",
    "markedAsRead": "படித்தது என்று குறியிடப்பட்டது",
    "previous": "முந்தைய",
    "next2": "அடுத்த",
    "completed": "முடிந்தது!",
    "endOfSeerah": "சீரத் முடிவு 🕊️",
    "chapterNotFound": "அத்தியாயம் கிடைக்கவில்லை",
    "currentPrayer": "தற்போதைய தொழுகை",
    "viewAllPrayers": "அனைத்து தொழுகைகளும் பார்க்க",
    "mainDuas": "முக்கிய துஆக்கள்",
    "otherDuas": "மற்ற துஆக்கள்",
    "completeGoalsToday": "இன்று {total} இலக்குகளை நிறைவேற்றுங்கள்",
    "quran": "குர்ஆன்",
    "page": "பக்கம்",
    "dhikr": "திக்ர்",
    "other": "மற்றவை",
  
    "mosqueFinder": "பள்ளிவாசல் தேடி",
    "halalFoodFinder": "ஹலால் உணவு தேடி",
    "pillarsOfIslam": "இஸ்லாத்தின் தூண்கள்",
    "zakatCalculator": "ஜகாத் கால்குலேட்டர்",
    "hajjUmrahGuide": "ஹஜ் & உம்ரா வழிகாட்டி",
  },
  te: {
    tasbihCounter: "తస్బీహ్ కౌంటర్",
    nobleQuran: "దివ్య ఖురాన్",
    hadithCollections: "హదీసుల సేకరణ",
    namesOfAllah: "అస్మా అల్-హుస్నా",
    prayerTimes: "నమాజ్ సమయాలు",
    qiblaFinder: "ఖిబ్లా దిశ",
    hijriCalendar: "హిజ్రీ క్యాలెండర్",
    favourites: "ఇష్టమైనవి",
    publications: "ప్రచురణలు",
    emotions: "భావోద్వేగాలు",
    reminders: "రిమైండర్లు",
    read: "చదవండి",
    listen: "వినండి",
    learn: "నేర్చుకోండి",
    surah: "సూరా",
    juz: "పారా",
    bookmark: "బుక్‌మార్క్",
    ayaat: "ఆయత్‌లు",
    changeLanguage: "భాష మార్చండి",
    appearance: "రూపం",
    notifications: "నోటిఫికேషన్లు",
    audio: "ఆడియో",
    system: "సిస్టమ్",
    more: "మరింత సమాచారం",
    savePreferences: "సేవ్ చేయండి",
    search: "వెతకండి...",
    resume: "కొనసాగించండి",
    cancel: "రద్దు",
    save: "సేవ్",
    back: "వెనుకకు",
  
    "lifeOfProphet": "ప్రవక్త ﷺ జీవితం",
    "sealedNectar": "అర్-రహీఖుల్ మఖ్తూమ్",
    "chaptersRead": "అధ్యాయాలు చదివారు",
    "searchChapters": "అధ్యాయాలు వెతకండి...",
    "all": "అన్నీ",
    "markAsRead": "చదివినట్లు గుర్తు",
    "markedAsRead": "చదివినట్లు గుర్తించారు",
    "previous": "మునుపటి",
    "next2": "తదుపరి",
    "completed": "పూర్తయింది!",
    "endOfSeerah": "సీరత్ ముగింపు 🕊️",
    "chapterNotFound": "అధ్యాయం కనుగొనబడలేదు",
    "currentPrayer": "ప్రస్తుత నమాజ్",
    "viewAllPrayers": "అన్ని నమాజులు చూడండి",
    "mainDuas": "ముఖ్య దుఆలు",
    "otherDuas": "ఇతర దుఆలు",
    "completeGoalsToday": "ఈరోజు {total} లక్ష్యాలు పూర్తి చేయండి",
    "quran": "ఖురాన్",
    "page": "పేజీ",
    "dhikr": "జిక్ర్",
    "other": "ఇతర",
  
    "mosqueFinder": "మసీదుల అన్వేషణ",
    "halalFoodFinder": "హలాల్ ఆహార అన్వేషణ",
    "pillarsOfIslam": "Pillars of Islam",
    "zakatCalculator": "Zakat Calculator",
    "hajjUmrahGuide": "Hajj & Umrah",
  },
  kn: {
    tasbihCounter: "ತಸ್ಬೀಹ್ ಕೌಂಟರ್",
    nobleQuran: "ದಿವ್ಯ ಕುರಾನ್",
    hadithCollections: "ಹದೀಸ್ ಸಂಗ್ರಹ",
    namesOfAllah: "ಅಸ್ಮಾ ಅಲ್-ಹುಸ್ನಾ",
    prayerTimes: "ನಮಾಜ್ ಸಮಯಗಳು",
    qiblaFinder: "ಕಿಬ್ಲಾ ದಿಕ್ಸೂಚಿ",
    hijriCalendar: "ಹಿಜ್ರಿ ಕ್ಯಾಲೆಂಡರ್",
    favourites: "ಮೆಚ್ಚಿನವುಗಳು",
    publications: "ಪ್ರಕಟಣೆಗಳು",
    emotions: "ಭಾವನೆಗಳು",
    reminders: "ಜ್ಞಾಪನೆಗಳು",
    read: "ಓದಿರಿ",
    listen: "ಕೇಳಿ",
    learn: "ಕಲಿಯಿರಿ",
    surah: "ಸೂರಾ",
    juz: "ಪಾರಾ",
    bookmark: "ಬುಕ್ಮಾರ್ಕ್",
    ayaat: "ಆಯತ್ಗಳು",
    changeLanguage: "ಭಾಷೆ ಬದಲಾಯಿಸಿ",
    appearance: "ಗೋಚರತೆ",
    notifications: "ಅಧಿಸೂಚನೆಗಳು",
    audio: "ಆಡಿಯೋ",
    system: "ವ್ಯವಸ್ಥೆ",
    more: "ಇನ್ನಷ್ಟು",
    savePreferences: "ಉಳಿಸಿ",
    search: "ಹುಡುಕಿ...",
    resume: "ಮುಂದುವರಿಸಿ",
    cancel: "ರದ್ದುಮಾಡು",
    save: "ಉಳಿಸು",
    back: "ಹಿಂದಕ್ಕೆ",
  
    "lifeOfProphet": "ಪ್ರವಾದಿ ﷺ ಜೀವನ",
    "sealedNectar": "ಅರ್-ರಹೀಖುಲ್ ಮಖ್ತೂಮ್",
    "chaptersRead": "ಅಧ್ಯಾಯಗಳನ್ನು ಓದಿದ್ದಾರೆ",
    "searchChapters": "ಅಧ್ಯಾಯಗಳನ್ನು ಹುಡುಕಿ...",
    "all": "ಎಲ್ಲ",
    "markAsRead": "ಓದಿದ್ದಾಗಿ ಗುರುತಿಸಿ",
    "markedAsRead": "ಓದಿದ್ದಾಗಿ ಗುರುತಿಸಲಾಗಿದೆ",
    "previous": "ಹಿಂದಿನ",
    "next2": "ಮುಂದಿನ",
    "completed": "ಪೂರ್ಣಗೊಂಡಿದೆ!",
    "endOfSeerah": "ಸೀರತ್ ಮುಕ್ತಾಯ 🕊️",
    "chapterNotFound": "ಅಧ್ಯಾಯ ಕಂಡುಬಂದಿಲ್ಲ",
    "currentPrayer": "ಪ್ರಸ್ತುತ ನಮಾಜ್",
    "viewAllPrayers": "ಎಲ್ಲ ನಮಾಜ್‌ಗಳನ್ನು ನೋಡಿ",
    "mainDuas": "ಮುಖ್ಯ ದುಆಗಳು",
    "otherDuas": "ಇತರ ದುಆಗಳು",
    "completeGoalsToday": "ಇಂದು {total} ಗುರಿಗಳನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ",
    "quran": "ಕುರ್ಆನ್",
    "page": "ಪುಟ",
    "dhikr": "ಜಿಕ್ರ್",
    "other": "ಇತರ",
  
    "mosqueFinder": "ಮಸೀದಿ ಅನ್ವೇಷಕ",
    "halalFoodFinder": "ಹಲಾಲ್ ಆಹಾರ ಅನ್ವೇಷಕ",
    "pillarsOfIslam": "Pillars of Islam",
    "zakatCalculator": "Zakat Calculator",
    "hajjUmrahGuide": "Hajj & Umrah",
  },
  ml: {
    tasbihCounter: "തസ്ബീഹ് കൗണ്ടർ",
    nobleQuran: "വിശുദ്ധ ഖുർആൻ",
    hadithCollections: "ഹദീസ് ശേഖരം",
    namesOfAllah: "അസ്മാഉൽ ഹുസ്ന",
    prayerTimes: "പ്രാർത്ഥന സമയം",
    qiblaFinder: "ഖിബ്‌ല ദിശ",
    hijriCalendar: "ഹിജ്‌റി കലണ്ടർ",
    favourites: "ഇಷ್ಟപ്പെട്ടവ",
    publications: "പ്രസിദ്ധീകരണങ്ങൾ",
    emotions: "വികാരങ്ങൾ",
    reminders: "ഓർമ്മപ്പെടുത്തലുകൾ",
    read: "വായിക്കുക",
    listen: "കേൾക്കുക",
    learn: "പഠിക്കുക",
    surah: "സൂറത്ത്",
    juz: "ജുസ്അ്",
    bookmark: "ബുക്ക്മാർക്ക്",
    ayaat: "ആയത്തുകൾ",
    changeLanguage: "ഭാഷ മാറ്റുക",
    appearance: "രൂപം",
    notifications: "അറിയിപ്പുകൾ",
    audio: "ഓഡിയോ",
    system: "സിസ്റ്റം",
    more: "കൂടുതൽ",
    savePreferences: "സേവ് ചെയ്യുക",
    search: "തിരയുക...",
    resume: "തുടരുക",
    cancel: "റദ്ദാക്കുക",
    save: "സേവ്",
    back: "പിന്നിലേക്ക്",
  
    "lifeOfProphet": "നബി ﷺ ജീവിതം",
    "sealedNectar": "അർ-റഹീഖുൽ മഖ്തൂം",
    "chaptersRead": "അധ്യായങ്ങൾ വായിച്ചു",
    "searchChapters": "അധ്യായങ്ങൾ തിരയുക...",
    "all": "എല്ലാം",
    "markAsRead": "വായിച്ചതായി അടയാളപ്പെടുത്തുക",
    "markedAsRead": "വായിച്ചതായി അടയാളപ്പെടുത്തി",
    "previous": "മുൻ",
    "next2": "അടുത്ത",
    "completed": "പൂർത്തിയായി!",
    "endOfSeerah": "സീറ സമാപ്തം 🕊️",
    "chapterNotFound": "അധ്യായം കണ്ടെത്തിയില്ല",
    "currentPrayer": "നിലവിലെ നമസ്‌കാരം",
    "viewAllPrayers": "എല്ലാ നമസ്‌കാരവും കാണുക",
    "mainDuas": "പ്രധാന ദുആകൾ",
    "otherDuas": "മറ്റ് ദുആകൾ",
    "completeGoalsToday": "ഇന്ന് {total} ലക്ഷ്യങ്ങൾ പൂർത്തിയാക്കുക",
    "quran": "ഖുർആൻ",
    "page": "പേജ്",
    "dhikr": "ദിക്ർ",
    "other": "മറ്റുള്ളവ",
  
    "mosqueFinder": "പള്ളി തിരച്ചിൽ",
    "halalFoodFinder": "ഹലാൽ ഭക്ഷണ തിരച്ചിൽ",
    "pillarsOfIslam": "Pillars of Islam",
    "zakatCalculator": "Zakat Calculator",
    "hajjUmrahGuide": "Hajj & Umrah",
  },
  gu: {
    tasbihCounter: "તસ્બીહ કાઉન્ટર",
    nobleQuran: "અલ-કુરાન",
    hadithCollections: "હદીસ સંગ્રહ",
    namesOfAllah: "અસ્મા અલ-હુસ્ના",
    prayerTimes: "નમાઝનો સમય",
    qiblaFinder: "કિબલા દિશા",
    hijriCalendar: "હિજરી કેલેન્ડર",
    favourites: "પસંદીદા",
    publications: "પ્રકાશન",
    emotions: "લાગણીઓ",
    reminders: "યાદ કરાવો",
    read: "વાંચો",
    listen: "સાંભળો",
    learn: "શીખો",
    surah: "સૂરા",
    juz: "પારા",
    bookmark: "બુકમાર્ક",
    ayaat: "આયાત",
    changeLanguage: "ભાષા બદલો",
    appearance: "દેખાવ",
    notifications: "નોટિફિકેશન",
    audio: "ઓડિયો",
    system: "સિસ્ટમ",
    more: "વધુ",
    savePreferences: "સેવ કરો",
    search: "શોધો...",
    resume: "ચાલુ રાખો",
    cancel: "રદ કરો",
    save: "સેવ",
    back: "પાછા",
  
    "lifeOfProphet": "પ્રોફेट ﷺ જીવન",
    "sealedNectar": "અર-રહીખુલ મખ્તૂમ",
    "chaptersRead": "પ્રકરણ વાંચ્યા",
    "searchChapters": "પ્રકરણ શોધો...",
    "all": "બધા",
    "markAsRead": "વાંચ્યા તરીકે ચિહ્નિત",
    "markedAsRead": "વાંચ્યા તરીકે ચિહ્નિત કર્યું",
    "previous": "પહેલા",
    "next2": "આગળ",
    "completed": "સંપૂર્ણ!",
    "endOfSeerah": "સીરત સમાપ્ત 🕊️",
    "chapterNotFound": "પ્રકરણ મળ્યું નથી",
    "currentPrayer": "વર્તમાન નમાઝ",
    "viewAllPrayers": "બધી નમાઝ જુઓ",
    "mainDuas": "મુખ્ય દુઆ",
    "otherDuas": "અન્ય દુઆ",
    "completeGoalsToday": "આજે {total} ધ્યેય પૂર્ણ કરો",
    "quran": "ક઼ુર'આન",
    "page": "પૃષ્ઠ",
    "dhikr": "ઝિક્ર",
    "other": "અન્ય",
  
    "mosqueFinder": "મસ્જિદ શોધક",
    "halalFoodFinder": "હલાલ ખોરાક શોધક",
    "pillarsOfIslam": "Pillars of Islam",
    "zakatCalculator": "Zakat Calculator",
    "hajjUmrahGuide": "Hajj & Umrah",
  },
  mr: {
    tasbihCounter: "तस्बीह काउंटर",
    nobleQuran: "कुराण शरीफ",
    hadithCollections: "हदीस संग्रह",
    namesOfAllah: "अस्मा अल-हुस्ना",
    prayerTimes: "नमाजची वेळ",
    qiblaFinder: "किबला दिशा",
    hijriCalendar: "हिजरी कॅलेंडर",
    favourites: "आवडते",
    publications: "प्रकाशने",
    emotions: "भावना",
    reminders: "स्मरणपत्रे",
    read: "वाचा",
    listen: "ऐका",
    learn: "शिका",
    surah: "सुरा",
    juz: "पारा",
    bookmark: "बुकमार्क",
    ayaat: "आयात",
    changeLanguage: "भाषा बदला",
    appearance: "देखावा",
    notifications: "अधिसूचना",
    audio: "ऑडिओ",
    system: "प्रणाली",
    more: "अधिक",
    savePreferences: "जतन करा",
    search: "शोधा...",
    resume: "पुन्हा सुरू करा",
    cancel: "रद्द करा",
    save: "जतन करा",
    back: "मागे",
  
    "lifeOfProphet": "नबी ﷺ यांचे जीवन",
    "sealedNectar": "अर-रहीखुल मख्तूम",
    "chaptersRead": "प्रकरणे वाचली",
    "searchChapters": "प्रकरणे शोधा...",
    "all": "सर्व",
    "markAsRead": "वाचलेले म्हणून चिन्हांकित करा",
    "markedAsRead": "वाचलेले म्हणून चिन्हांकित",
    "previous": "मागील",
    "next2": "पुढील",
    "completed": "पूर्ण!",
    "endOfSeerah": "सीरत संपली 🕊️",
    "chapterNotFound": "प्रकरण सापडले नाही",
    "currentPrayer": "सध्याची नमाज",
    "viewAllPrayers": "सर्व नमाज पाहा",
    "mainDuas": "मुख्य दुआ",
    "otherDuas": "इतर दुआ",
    "completeGoalsToday": "आज {total} उद्दिष्टे पूर्ण करा",
    "quran": "कुरआन",
    "page": "पृष्ठ",
    "dhikr": "जिक्र",
    "other": "इतर",
  
    "mosqueFinder": "मस्जिद शोधक",
    "halalFoodFinder": "हलाल अन्न शोधक",
    "pillarsOfIslam": "Pillars of Islam",
    "zakatCalculator": "Zakat Calculator",
    "hajjUmrahGuide": "Hajj & Umrah",
  },
  pa: {
    tasbihCounter: "ਤਸਬੀਹ ਕਾਊਂਟਰ",
    nobleQuran: "ਅਲ-ਕੁਰਾਨ",
    hadithCollections: "ਹਦੀਸ ਸੰਗ੍ਰਹਿ",
    namesOfAllah: "ਅਸਮਾ ਅਲ-ਹੁਸਨਾ",
    prayerTimes: "ਨਮਾਜ਼ ਦਾ ਸਮਾਂ",
    qiblaFinder: "ਕਿਬਲਾ ਦਿਸ਼ਾ",
    hijriCalendar: "ਹਿਜਰੀ ਕੈਲੰਡर",
    favourites: "ਮਨਪਸੰਦ",
    publications: "ਪ੍ਰਕਾਸ਼ਨ",
    emotions: "ਭਾਵਨਾਵਾਂ",
    reminders: "ਯਾਦ ਪੱਤਰ",
    read: "ਪੜ੍ਹੋ",
    listen: "ਸੁਣੋ",
    learn: "ਸਿੱਖੋ",
    surah: "ਸੂਰਾ",
    juz: "ਪਾਰਾ",
    bookmark: "ਬੁੱਕਮार्क",
    ayaat: "ਆਇਤਾਂ",
    changeLanguage: "ਭาਸ਼ਾ ਬਦਲੋ",
    appearance: "ਦਿੱਖ",
    notifications: "ਨੋਟੀਫਿਕੇਸ਼ਨ",
    audio: "ਆਡੀਓ",
    system: "ਸਿਸਟਮ",
    more: "ਹੋਰ",
    savePreferences: "ਸੇਵ ਕਰੋ",
    search: "ਲੱਭੋ...",
    resume: "ਜਾਰੀ ਰੱਖੋ",
    cancel: "ਰੱਦ ਕਰੋ",
    save: "ਸੇਵ",
    back: "ਪਿੱਛੇ",
  
    "lifeOfProphet": "ਨਬੀ ﷺ ਦੀ ਜ਼ਿੰਦਗੀ",
    "sealedNectar": "ਅਰ-ਰਹੀਖੁਲ ਮਖਤੂਮ",
    "chaptersRead": "ਅਧਿਆਏ ਪੜ੍ਹੇ",
    "searchChapters": "ਅਧਿਆਏ ਭਾਲੋ...",
    "all": "ਸਾਰੇ",
    "markAsRead": "ਪੜ੍ਹੇ ਵਜੋਂ ਨਿਸ਼ਾਨ ਕਰੋ",
    "markedAsRead": "ਪੜ੍ਹੇ ਵਜੋਂ ਨਿਸ਼ਾਨ ਕੀਤਾ",
    "previous": "ਪਿਛਲਾ",
    "next2": "ਅਗਲਾ",
    "completed": "ਪੂਰਾ!",
    "endOfSeerah": "ਸੀਰਤ ਖਤਮ 🕊️",
    "chapterNotFound": "ਅਧਿਆਏ ਨਹੀਂ ਮਿਲਿਆ",
    "currentPrayer": "ਮੌਜੂਦਾ ਨਮਾਜ਼",
    "viewAllPrayers": "ਸਾਰੀਆਂ ਨਮਾਜ਼ਾਂ ਦੇਖੋ",
    "mainDuas": "ਮੁੱਖ ਦੁਆਵਾਂ",
    "otherDuas": "ਹੋਰ ਦੁਆਵਾਂ",
    "completeGoalsToday": "ਅੱਜ {total} ਟੀਚੇ ਪੂਰੇ ਕਰੋ",
    "quran": "ਕੁਰਆਨ",
    "page": "ਪੰਨਾ",
    "dhikr": "ਜ਼ਿਕਰ",
    "other": "ਹੋਰ",
  
    "mosqueFinder": "ਮਸਜਿਦ ਖੋਜੀ",
    "halalFoodFinder": "ਹਲਾਲ ਭੋਜਨ ਖੋਜੀ",
    "pillarsOfIslam": "Pillars of Islam",
    "zakatCalculator": "Zakat Calculator",
    "hajjUmrahGuide": "Hajj & Umrah",
  },
  ru: {
    tasbihCounter: "Тасбих счетчик",
    nobleQuran: "Священный Коран",
    hadithCollections: "Сборники хадисов",
    namesOfAllah: "Асма аль-Хусна",
    prayerTimes: "Время намаза",
    qiblaFinder: "Направление Киблы",
    hijriCalendar: "Исламский календарь",
    favourites: "Избранное",
    publications: "Публикации",
    emotions: "Чувства",
    reminders: "Напоминания",
    read: "Читать",
    listen: "Слушать",
    learn: "Учить Коран",
    surah: "Сура",
    juz: "Джуз",
    bookmark: "Закладка",
    ayaat: "Аяты",
    changeLanguage: "Изменить язык",
    appearance: "Оформление",
    notifications: "Уведомления",
    audio: "Аудио",
    system: "Система",
    more: "Дополнительно",
    savePreferences: "Сохранить",
    search: "Поиск...",
    resume: "Продолжить",
    cancel: "Отмена",
    save: "Сохранить",
    back: "Назад",
  
    "lifeOfProphet": "Жизнь Пророка ﷺ",
    "sealedNectar": "Ар-Рахик аль-Махтум",
    "chaptersRead": "глав прочитано",
    "searchChapters": "Поиск глав...",
    "all": "Все",
    "markAsRead": "Отметить как прочитанное",
    "markedAsRead": "Отмечено как прочитанное",
    "previous": "Предыдущий",
    "next2": "Следующий",
    "completed": "Завершено!",
    "endOfSeerah": "Конец Сиры 🕊️",
    "chapterNotFound": "Глава не найдена",
    "currentPrayer": "Текущий Намаз",
    "viewAllPrayers": "Все Намазы",
    "mainDuas": "Основные Дуа",
    "otherDuas": "Другие Дуа",
    "completeGoalsToday": "Выполнить {total} целей сегодня",
    "quran": "Коран",
    "page": "Страница",
    "dhikr": "Зикр",
    "other": "Другое",
  
    "mosqueFinder": "Поиск мечетей",
    "halalFoodFinder": "Поиск халяльной еды",
    "pillarsOfIslam": "Pillars of Islam",
    "zakatCalculator": "Zakat Calculator",
    "hajjUmrahGuide": "Hajj & Umrah",
  },
  so: {
    tasbihCounter: "Tusbax Erayga",
    nobleQuran: "Qur'aanka Kariimka",
    hadithCollections: "Kutubta Xadiiska",
    namesOfAllah: "Asma Al-Husna",
    prayerTimes: "Afafta Salaada",
    qiblaFinder: "Jihooyinka Qiblada",
    hijriCalendar: "Hicri Kalandarka",
    favourites: "Xulashada",
    publications: "Maqaalo",
    emotions: "Dareenka",
    reminders: "Xusuusiyaha",
    read: "Akhriso",
    listen: "Dhageyso",
    learn: "Baro",
    surah: "Suurad",
    juz: "Juz",
    bookmark: "Calaamadee",
    ayaat: "Aayado",
    changeLanguage: "Beddel Luqadda",
    appearance: "Muuqaalka",
    notifications: "Ogeysiisyada",
    audio: "Codka",
    system: "Habka App-ka",
    more: "Kordhi",
    savePreferences: "Keydi doorashada",
    search: "Raadi...",
    resume: "Halkaad joogtay",
    cancel: "Ka noqo",
    save: "Keydi",
    back: "Dib u laabo",
  
    "lifeOfProphet": "Nolosha Nabiga ﷺ",
    "sealedNectar": "Ar-Rahiiqul Makhtuum",
    "chaptersRead": "cutubbo la akhristay",
    "searchChapters": "Raadi cutubbo...",
    "all": "Dhammaan",
    "markAsRead": "Calaamadee inuu La Akhriyay",
    "markedAsRead": "Waxaa Calaamadaysan inuu La Akhriyay",
    "previous": "Hore",
    "next2": "Xiga",
    "completed": "La Dhameeyay!",
    "endOfSeerah": "Dhamaadka Siiraha 🕊️",
    "chapterNotFound": "Cutubka lama helin",
    "currentPrayer": "Salaadda Hadda",
    "viewAllPrayers": "Arag Dhammaan Salaaduhu",
    "mainDuas": "Ducada Koowaad",
    "otherDuas": "Ducooyin Kale",
    "completeGoalsToday": "Dhammaystir {total} bartilmaameed maanta",
    "quran": "Quraanka",
    "page": "Bogga",
    "dhikr": "Xusus",
    "other": "Kale",
  
    "mosqueFinder": "Helaha Masaajidda",
    "halalFoodFinder": "Helaha Cuntada Xalaasha ah",
    "pillarsOfIslam": "Pillars of Islam",
    "zakatCalculator": "Zakat Calculator",
    "hajjUmrahGuide": "Hajj & Umrah",
  },
  uz: {
    tasbihCounter: "Tasbeh hisoblagich",
    nobleQuran: "Qur'oni Karim",
    hadithCollections: "Hadis to'plamlari",
    namesOfAllah: "Asmoul Husno",
    prayerTimes: "Namoz vaqtlari",
    qiblaFinder: "Qibla yo'nalishi",
    hijriCalendar: "Hijriy taqvim",
    favourites: "Saralanganlar",
    publications: "Maqolalar",
    emotions: "Hissiyotlar",
    reminders: "Eslatmalar",
    read: "O'qish",
    listen: "Tinglash",
    learn: "O'rganish",
    surah: "Sura",
    juz: "Poralar",
    bookmark: "Xatcho'p",
    ayaat: "Oyatlar",
    changeLanguage: "Tilni o'zgartirish",
    appearance: "Ko'rinish",
    notifications: "Bildirishnomalar",
    audio: "Audio",
    system: "Tizim",
    more: "Batafsil",
    savePreferences: "Saqlash",
    search: "Qidiruv...",
    resume: "Davom etish",
    cancel: "Bekor qilish",
    save: "Saqlash",
    back: "Orqaga",
  
    "lifeOfProphet": "Payg'ambar ﷺ hayoti",
    "sealedNectar": "Ar-Rahiqul Maktum",
    "chaptersRead": "bob o'qildi",
    "searchChapters": "Boblarni qidiring...",
    "all": "Hammasi",
    "markAsRead": "O'qilgan deb belgilash",
    "markedAsRead": "O'qilgan deb belgilandi",
    "previous": "Oldingi",
    "next2": "Keyingi",
    "completed": "Tugallandi!",
    "endOfSeerah": "Siyrat tugadi 🕊️",
    "chapterNotFound": "Bob topilmadi",
    "currentPrayer": "Joriy namoz",
    "viewAllPrayers": "Barcha namozlarni ko'rish",
    "mainDuas": "Asosiy duolar",
    "otherDuas": "Boshqa duolar",
    "completeGoalsToday": "Bugun {total} maqsadni bajaring",
    "quran": "Qur'on",
    "page": "Sahifa",
    "dhikr": "Zikr",
    "other": "Boshqa",
  
    "mosqueFinder": "Masjid topuvchi",
    "halalFoodFinder": "Halol taom topuvchi",
    "pillarsOfIslam": "Pillars of Islam",
    "zakatCalculator": "Zakat Calculator",
    "hajjUmrahGuide": "Hajj & Umrah",
  },
  yo: {
    tasbihCounter: "Onka Tasbih",
    nobleQuran: "Al-Qur'an yi to mọ́",
    hadithCollections: "Kojọpọ Hadisi",
    namesOfAllah: "Asma Al-Husna",
    prayerTimes: "Wakati Irun",
    qiblaFinder: "Itọsọna Qibla",
    hijriCalendar: "Kalandar Hijri",
    favourites: "Awọn ayanfẹ",
    publications: "Awọn iwe itẹjade",
    emotions: "Awọn imọlara",
    reminders: "Awọn oluranti",
    read: "Ka",
    listen: "Gbọ́",
    learn: "Kọ́ ẹkọ",
    surah: "Surah",
    juz: "Juz",
    bookmark: "Àmì ìwé",
    ayaat: "Awọn ẹsẹ",
    changeLanguage: "Yi ede pada",
    appearance: "Irisi",
    notifications: "Awọn iwifunni",
    audio: "Audio",
    system: "Eto App",
    more: "Diẹ sii",
    savePreferences: "Fi pamọ",
    search: "Wa...",
    resume: "Tẹsiwaju",
    cancel: "Fagile",
    save: "Fi pamọ",
    back: "Pada",
  
    "lifeOfProphet": "Igbesi Aiye Annabi ﷺ",
    "sealedNectar": "Ar-Rahiiqul Makhtuum",
    "chaptersRead": "abala ti a ka",
    "searchChapters": "Wa awọn abala...",
    "all": "Gbogbo",
    "markAsRead": "Fi Ami pe Ti Ka",
    "markedAsRead": "Fi Ami pe Ti Ka tẹlẹ",
    "previous": "Ẹyọ Ti Kọja",
    "next2": "Ẹyọ Ti Mbọ",
    "completed": "Pari!",
    "endOfSeerah": "Opin Sirah 🕊️",
    "chapterNotFound": "Ko ri abala",
    "currentPrayer": "Salah Lọwọlọwọ",
    "viewAllPrayers": "Wo Gbogbo Salah",
    "mainDuas": "Awọn Dua Pataki",
    "otherDuas": "Awọn Dua Miiran",
    "completeGoalsToday": "Pari {total} ibi-afẹde loni",
    "quran": "Al-Qur'an",
    "page": "Oju-iwe",
    "dhikr": "Dhikr",
    "other": "Miiran",
  
    "mosqueFinder": "Oluwari Mossalasi",
    "halalFoodFinder": "Oluwari Ounje Halal",
    "pillarsOfIslam": "Pillars of Islam",
    "zakatCalculator": "Zakat Calculator",
    "hajjUmrahGuide": "Hajj & Umrah",
  },
  ps: {
    tasbihCounter: "د تسبيح حسابونکی",
    nobleQuran: "قرآن کريم",
    hadithCollections: "د حديثونو ټولګې",
    namesOfAllah: "اسماء الحسنیٰ",
    prayerTimes: "د لمانځه وختونه",
    qiblaFinder: "قبله ښودونکی",
    hijriCalendar: "قمري هجري کلیز",
    favourites: "خوښ شوي",
    publications: "خپرونې",
    emotions: "احساسات",
    reminders: "یادونې",
    read: "لوستل",
    listen: "اوریدل",
    learn: "زده کړه",
    surah: "سورة",
    juz: "پاره",
    bookmark: "نښه کول",
    ayaat: "آیتونه",
    changeLanguage: "ژبه بدلول",
    appearance: "ظاهر",
    notifications: "خبرتیاوې",
    audio: "غږونه",
    system: "سیستم",
    more: "نور",
    savePreferences: "تنظیمات خوندي کول",
    search: "لټون...",
    resume: "دوام ورکول",
    cancel: "لغوه کول",
    save: "خوندي کول",
    back: "شاته تلل",
  
    "lifeOfProphet": "د پیغمبر ﷺ ژوند",
    "sealedNectar": "الرحیق المختوم",
    "chaptersRead": "فصلونه لوستل شوي",
    "searchChapters": "فصلونه وپلټئ...",
    "all": "ټول",
    "markAsRead": "د لوستل نښه کول",
    "markedAsRead": "د لوستل نښه شو",
    "previous": "مخکینی",
    "next2": "راتلونکی",
    "completed": "بشپړ!",
    "endOfSeerah": "د سیرت پای 🕊️",
    "chapterNotFound": "فصل و نه موندل شو",
    "currentPrayer": "اوسنۍ لمونځ",
    "viewAllPrayers": "ټول لمونځونه وګورئ",
    "mainDuas": "لوی دعاګانې",
    "otherDuas": "نورې دعاګانې",
    "completeGoalsToday": "نن {total} هدفونه بشپړ کړئ",
    "quran": "قرآن",
    "page": "پاڼه",
    "dhikr": "ذکر",
    "other": "نور",
  
    "mosqueFinder": "د جومات لټونکی",
    "halalFoodFinder": "د حلال خواړو لټونکی",
    "pillarsOfIslam": "Pillars of Islam",
    "zakatCalculator": "Zakat Calculator",
    "hajjUmrahGuide": "Hajj & Umrah",
  }
};

export function useTranslation(currentLang: string) {
  const t = (key: string): string => {
    const langDict = TRANSLATIONS[currentLang] || TRANSLATIONS.en;
    return langDict[key] || TRANSLATIONS.en[key] || key;
  };
  return { t };
}
